/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out and revoke the session family */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/chart-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your chart preferences
         * @description Defaults, not a 404, when nothing has ever been saved.
         *
         *     A client that has to special-case "no preferences yet" will get it wrong on
         *     first load, and there is no meaningful difference between "unset" and "set
         *     to the defaults".
         */
        get: operations["chart_get_chart_preferences"];
        /**
         * Replace your chart preferences
         * @description Full replacement, not a patch. A second PUT replaces rather than merges.
         */
        put: operations["chart_put_chart_preferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API metadata */
        get: operations["meta_get_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get quotes by ticker
         * @description Cache-first. Anything past the TTL is refetched, the rest is served as stored.
         *
         *     Unknown tickers are simply absent from the response rather than failing it.
         */
        get: operations["market-data_get_quotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search symbols
         * @description Trigram search over ticker and name. Exact ticker matches rank first.
         */
        get: operations["market-data_search_symbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one symbol */
        get: operations["market-data_get_symbol"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{ticker}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily bars for one symbol
         * @description OHLCV, oldest first. Unknown ticker is 404; range plus start/end is 422.
         */
        get: operations["market-data_get_bars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Computed indicators for one symbol
         * @description The same window as the bars endpoint, aligned by ``trade_date``.
         *
         *     Nulls are real: a 200-day average has no value for its first 199 bars, and
         *     the chart must draw a gap there rather than a line to zero.
         */
        get: operations["market-data_get_indicators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your watchlists */
        get: operations["watchlists_list_watchlists"];
        put?: never;
        /**
         * Create a watchlist
         * @description 409 when the name is already taken — names are unique per user.
         */
        post: operations["watchlists_create_watchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a watchlist */
        get: operations["watchlists_get_watchlist"];
        put?: never;
        post?: never;
        /** Delete a watchlist */
        delete: operations["watchlists_delete_watchlist"];
        options?: never;
        head?: never;
        /** Rename a watchlist */
        patch: operations["watchlists_update_watchlist"];
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a symbol to a watchlist
         * @description 409 if the symbol is already on the list; 404 if the ticker is unknown.
         */
        post: operations["watchlists_add_item"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder a watchlist
         * @description Takes the complete ordering; a partial list is a 422.
         */
        patch: operations["watchlists_reorder_items"];
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a symbol from a watchlist */
        delete: operations["watchlists_remove_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The quote grid for a watchlist
         * @description The endpoint the grid polls: one request, one joined read.
         *
         *     Stale quotes are refreshed first so that polling this actually moves the
         *     prices, then the rows come back from a single join rather than a query per
         *     item. Refreshing is cache-first and bounded by the quote TTL, so polling
         *     faster than the TTL costs nothing upstream.
         */
        get: operations["watchlists_watchlist_quotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Is the process up? Never touches a dependency.
         */
        get: operations["health_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Can the process serve traffic?
         *
         *     Note that a ``false`` in ``checks`` does not necessarily mean ``not_ready``:
         *     only the checks in ``_REQUIRED_CHECKS`` decide the status. The rest are
         *     surfaced so an operator can see a degraded dependency without a pager going
         *     off for it.
         */
        get: operations["health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BarResponse */
        BarResponse: {
            /** Close */
            close: string;
            /** High */
            high: string;
            /** Is Adjusted */
            is_adjusted: boolean;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Volume */
            volume: number;
        };
        /**
         * BarsResponse
         * @description One symbol's OHLCV window, oldest first.
         *
         *     Carries the ticker so a client holding several in flight can tell them
         *     apart without threading the request parameters back through.
         */
        BarsResponse: {
            /** Bars */
            bars: components["schemas"]["BarResponse"][];
            /** Ticker */
            ticker: string;
        };
        /**
         * ChartPreferencesRequest
         * @description A full replacement, not a patch — every field is required.
         *
         *     A PATCH shape would need a way to say "no overlays at all" that is distinct
         *     from "leave them alone", and `null` versus `[]` is exactly the distinction
         *     clients get wrong.
         */
        ChartPreferencesRequest: {
            /** Active Oscillators */
            active_oscillators?: components["schemas"]["Oscillator"][];
            /** Active Overlays */
            active_overlays?: components["schemas"]["PriceOverlay"][];
            default_range: components["schemas"]["ChartRange"];
        };
        /**
         * ChartPreferencesResponse
         * @description What the controls are seeded from.
         *
         *     Returned with defaults filled in when the user has never saved anything, so
         *     a client never has to special-case "no preferences yet".
         */
        ChartPreferencesResponse: {
            /** Active Oscillators */
            active_oscillators: components["schemas"]["Oscillator"][];
            /** Active Overlays */
            active_overlays: components["schemas"]["PriceOverlay"][];
            default_range: components["schemas"]["ChartRange"];
        };
        /**
         * ChartRange
         * @description A window of history, expressed the way a chart toolbar expresses it.
         *
         *     Shared by the bars and indicators query strings and by the stored chart
         *     preference, which is why one enum serves all three rather than each layer
         *     inventing its own string set.
         *
         *     ``MAX`` means "everything stored", bounded by the row cap in
         *     ``app.services.chart_service`` rather than by a date.
         * @enum {string}
         */
        ChartRange: "1M" | "3M" | "6M" | "1Y" | "2Y" | "MAX";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * IndicatorResponse
         * @description Null means "not enough history yet", never zero.
         */
        IndicatorResponse: {
            /** Atr 14 */
            atr_14?: string | null;
            /** Ema 12 */
            ema_12?: string | null;
            /** Ema 26 */
            ema_26?: string | null;
            /** Macd */
            macd?: string | null;
            /** Macd Histogram */
            macd_histogram?: string | null;
            /** Macd Signal */
            macd_signal?: string | null;
            /** Rsi 14 */
            rsi_14?: string | null;
            /** Sma 20 */
            sma_20?: string | null;
            /** Sma 200 */
            sma_200?: string | null;
            /** Sma 50 */
            sma_50?: string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Volume Sma 20 */
            volume_sma_20?: string | null;
        };
        /**
         * IndicatorsResponse
         * @description The same window as ``BarsResponse``, same order, aligned by trade date.
         *
         *     Two responses rather than one combined payload: they are two parallel round
         *     trips rather than an N+1, and they stay independently useful — Phase 4 wants
         *     indicators without bars, and an export wants bars without indicators.
         */
        IndicatorsResponse: {
            /** Indicators */
            indicators: components["schemas"]["IndicatorResponse"][];
            /** Ticker */
            ticker: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Api Version */
            api_version: string;
            /** Environment */
            environment: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * Oscillator
         * @description Indicators that get a pane of their own, because their scale is not price.
         * @enum {string}
         */
        Oscillator: "rsi_14" | "macd";
        /**
         * PriceOverlay
         * @description Indicators drawn on the price pane, in price units.
         *
         *     Only moving averages qualify: an overlay has to share the candles' y-scale
         *     to mean anything, which rules out RSI (0-100) and MACD (centred on zero).
         *     Each value is a column of ``daily_indicators``.
         * @enum {string}
         */
        PriceOverlay: "sma_20" | "sma_50" | "sma_200" | "ema_12" | "ema_26";
        /**
         * QuoteResponse
         * @description A price, with both timestamps.
         *
         *     ``quoted_at`` is the provider's view of when this price was true;
         *     ``fetched_at`` is when we last asked. The client needs both to render "as
         *     of" honestly — a stale weekend price is not the same thing as a broken
         *     ingest, and a UI that only has one timestamp cannot tell the difference.
         *
         *     Every price is a string over the wire, because ``Decimal`` serialised as a
         *     JSON number would be parsed back into a float by every JavaScript client
         *     and quietly lose precision.
         */
        QuoteResponse: {
            /** Change */
            change?: string | null;
            /** Change Percent */
            change_percent?: string | null;
            /** Day High */
            day_high?: string | null;
            /** Day Low */
            day_low?: string | null;
            /** Day Open */
            day_open?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Previous Close */
            previous_close?: string | null;
            /** Price */
            price: string;
            /** Quoted At */
            quoted_at?: string | null;
            /** Ticker */
            ticker: string;
            /** Volume */
            volume?: number | null;
        };
        /**
         * QuotesResponse
         * @description Keyed by ticker.
         *
         *     A ticker that was asked for but is absent from the map was either unknown
         *     or has never been priced; the client renders those as blanks rather than
         *     treating the whole request as failed.
         */
        QuotesResponse: {
            /** Quotes */
            quotes?: {
                [key: string]: components["schemas"]["QuoteResponse"];
            };
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /**
             * Degraded
             * @default []
             */
            degraded: string[];
            /** Status */
            status: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SymbolResponse
         * @description One instrument in the universe.
         */
        SymbolResponse: {
            /** Asset Type */
            asset_type: string;
            /** Currency */
            currency: string;
            /** Exchange */
            exchange: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
        };
        /** SymbolSearchResponse */
        SymbolSearchResponse: {
            /** Items */
            items: components["schemas"]["SymbolResponse"][];
        };
        /**
         * TokenResponse
         * @description The access token. The refresh token travels as an HttpOnly cookie.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserResponse
         * @description A user as the API returns it.
         *
         *     Deliberately narrow: ``hashed_password`` has no business leaving the
         *     process, so it is not a field here rather than being excluded later.
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistCreateRequest */
        WatchlistCreateRequest: {
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Name */
            name: string;
        };
        /** WatchlistDetailResponse */
        WatchlistDetailResponse: {
            /** Rows */
            rows: components["schemas"]["WatchlistRowResponse"][];
            watchlist: components["schemas"]["WatchlistResponse"];
        };
        /** WatchlistItemCreateRequest */
        WatchlistItemCreateRequest: {
            /** Notes */
            notes?: string | null;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string | null;
            /** Position */
            position: number;
            /**
             * Symbol Id
             * Format: uuid
             */
            symbol_id: string;
        };
        /**
         * WatchlistReorderRequest
         * @description The full ordering, not a moved pair.
         *
         *     A partial reorder has no well-defined answer for the items it leaves out,
         *     and the drag-and-drop UI already knows the complete order it wants.
         */
        WatchlistReorderRequest: {
            /** Item Ids */
            item_ids: string[];
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Default */
            is_default: boolean;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WatchlistRowResponse
         * @description One line of the quote grid: the item, its symbol, and its latest price.
         *
         *     Flattened into a single object per row on purpose — the grid renders rows,
         *     and making the client stitch three collections together is how N+1 gets
         *     reinvented on the frontend.
         */
        WatchlistRowResponse: {
            item: components["schemas"]["WatchlistItemResponse"];
            quote?: components["schemas"]["QuoteResponse"] | null;
            symbol: components["schemas"]["SymbolResponse"];
        };
        /**
         * WatchlistUpdateRequest
         * @description Every field optional — this is a PATCH, so absent means "leave alone".
         */
        WatchlistUpdateRequest: {
            /** Is Default */
            is_default?: boolean | null;
            /** Name */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chart_get_chart_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPreferencesResponse"];
                };
            };
        };
    };
    chart_put_chart_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartPreferencesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_get_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    "market-data_get_quotes": {
        parameters: {
            query: {
                /** @description Comma-separated tickers, e.g. AAPL,MSFT */
                tickers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "market-data_search_symbols": {
        parameters: {
            query: {
                search: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "market-data_get_symbol": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "market-data_get_bars": {
        parameters: {
            query?: {
                /** @description A preset window (1M, 3M, 6M, 1Y, 2Y, MAX). Mutually exclusive with start/end. */
                range?: components["schemas"]["ChartRange"] | null;
                /** @description Explicit window start. Requires 'end' and excludes 'range'. */
                start?: string | null;
                /** @description Explicit window end. Requires 'start' and excludes 'range'. */
                end?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "market-data_get_indicators": {
        parameters: {
            query?: {
                /** @description A preset window (1M, 3M, 6M, 1Y, 2Y, MAX). Mutually exclusive with start/end. */
                range?: components["schemas"]["ChartRange"] | null;
                /** @description Explicit window start. Requires 'end' and excludes 'range'. */
                start?: string | null;
                /** @description Explicit window end. Requires 'start' and excludes 'range'. */
                end?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_list_watchlists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"][];
                };
            };
        };
    };
    watchlists_create_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_get_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_delete_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_update_watchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_add_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_reorder_items: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_remove_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlists_watchlist_quotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
