"""add 52w and change percent indicator columns

Revision ID: bafd78ac6767
Revises: f2de38bbeeb7
Create Date: 2026-08-22 11:36:03.329226

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "bafd78ac6767"
down_revision: str | None = "f2de38bbeeb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_daily_bars_trade_date", "daily_bars", ["trade_date"], unique=False)
    op.add_column(
        "daily_indicators",
        sa.Column("change_percent_1d", sa.Numeric(precision=18, scale=6), nullable=True),
    )
    op.add_column(
        "daily_indicators", sa.Column("high_52w", sa.Numeric(precision=18, scale=6), nullable=True)
    )
    op.add_column(
        "daily_indicators", sa.Column("low_52w", sa.Numeric(precision=18, scale=6), nullable=True)
    )
    op.create_index(
        "ix_daily_indicators_trade_date", "daily_indicators", ["trade_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_daily_indicators_trade_date", table_name="daily_indicators")
    op.drop_column("daily_indicators", "low_52w")
    op.drop_column("daily_indicators", "high_52w")
    op.drop_column("daily_indicators", "change_percent_1d")
    op.drop_index("ix_daily_bars_trade_date", table_name="daily_bars")
    # ### end Alembic commands ###
